name: Scheduled API Call

on:
  schedule:
    - cron: '0 * * * *'  # Chạy mỗi giờ (0 phút của mỗi giờ)
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: curl -X GET "https://ts-store-nodejs-noti.vercel.app/ping-cron"
